@UniGroup.CRM.API_HostAddress = https://localhost:7170

### Register a new user
POST {{UniGroup.CRM.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "testuser@unigroup.com",
  "password": "Password123!",
  "firstName": "Test",
  "lastName": "User"
}

###

### Login as the registered user
POST {{UniGroup.CRM.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "testuser@unigroup.com",
  "password": "Password123!"
}

###

